create extension if not exists unaccent with schema extensions;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.make_slug(source_text text)
returns text
language sql
immutable
as $$
  select trim(
    both '-'
    from regexp_replace(
      lower(extensions.unaccent(coalesce(source_text, ''))),
      '[^a-z0-9]+',
      '-',
      'g'
    )
  );
$$;

create or replace function public.apply_slug()
returns trigger
language plpgsql
as $$
begin
  new.slug = public.make_slug(new.name);
  return new;
end;
$$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users (id) on delete cascade,
  name text not null,
  email text not null unique,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories (id) on delete cascade,
  name text not null,
  slug text not null unique,
  description text,
  price numeric(10, 2) not null default 0,
  purchase_price numeric(10, 2),
  sale_price numeric(10, 2),
  stock_quantity integer not null default 0,
  minimum_stock integer not null default 10,
  barcode text unique,
  image_path text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade,
  user_id bigint not null references public.users (id) on delete cascade,
  type text not null check (type in ('in', 'out')),
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null default 0,
  purchase_price numeric(10, 2),
  sale_price numeric(10, 2),
  total_price numeric(10, 2),
  notes text,
  deleted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
before update on public.categories
for each row
execute function public.set_updated_at();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

drop trigger if exists transactions_set_updated_at on public.transactions;
create trigger transactions_set_updated_at
before update on public.transactions
for each row
execute function public.set_updated_at();

drop trigger if exists categories_apply_slug on public.categories;
create trigger categories_apply_slug
before insert or update of name on public.categories
for each row
execute function public.apply_slug();

drop trigger if exists products_apply_slug on public.products;
create trigger products_apply_slug
before insert or update of name on public.products
for each row
execute function public.apply_slug();

create or replace function public.handle_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (auth_user_id, name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1), 'Utilisateur'),
    new.email,
    'user'
  )
  on conflict (auth_user_id) do update
  set
    name = excluded.name,
    email = excluded.email,
    updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update on auth.users
for each row
execute function public.handle_auth_user();

create or replace function public.current_app_user_id()
returns bigint
language sql
stable
as $$
  select u.id
  from public.users u
  where u.auth_user_id = auth.uid()
  limit 1;
$$;

create or replace function public.get_low_stock_products()
returns jsonb
language sql
stable
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', p.id,
        'category_id', p.category_id,
        'name', p.name,
        'slug', p.slug,
        'description', p.description,
        'price', p.price,
        'stock_quantity', p.stock_quantity,
        'minimum_stock', p.minimum_stock,
        'barcode', p.barcode,
        'image_path', p.image_path,
        'purchase_price', p.purchase_price,
        'sale_price', p.sale_price,
        'created_at', p.created_at,
        'updated_at', p.updated_at,
        'category', jsonb_build_object(
          'id', c.id,
          'name', c.name,
          'slug', c.slug,
          'description', c.description,
          'created_at', c.created_at,
          'updated_at', c.updated_at
        )
      )
      order by p.created_at desc
    ),
    '[]'::jsonb
  )
  from public.products p
  join public.categories c on c.id = p.category_id
  where p.stock_quantity <= p.minimum_stock;
$$;

create or replace function public.get_transaction_statistics()
returns jsonb
language sql
stable
as $$
  with recent as (
    select
      t.id,
      t.product_id,
      t.user_id,
      t.type,
      t.quantity,
      t.unit_price,
      t.total_price,
      t.purchase_price,
      t.sale_price,
      t.notes,
      t.created_at,
      t.updated_at,
      jsonb_build_object(
        'id', p.id,
        'category_id', p.category_id,
        'name', p.name,
        'slug', p.slug,
        'description', p.description,
        'price', p.price,
        'stock_quantity', p.stock_quantity,
        'minimum_stock', p.minimum_stock,
        'barcode', p.barcode,
        'image_path', p.image_path,
        'purchase_price', p.purchase_price,
        'sale_price', p.sale_price,
        'created_at', p.created_at,
        'updated_at', p.updated_at
      ) as product,
      jsonb_build_object(
        'id', u.id,
        'name', u.name,
        'email', u.email,
        'role', u.role
      ) as "user"
    from public.transactions t
    join public.products p on p.id = t.product_id
    join public.users u on u.id = t.user_id
    where t.deleted_at is null
    order by t.created_at desc
    limit 5
  )
  select jsonb_build_object(
    'total_in', coalesce((select sum(total_price) from public.transactions where type = 'in' and deleted_at is null), 0),
    'total_out', coalesce((select sum(total_price) from public.transactions where type = 'out' and deleted_at is null), 0),
    'total_transactions', coalesce((select count(*) from public.transactions where deleted_at is null), 0),
    'recent_transactions', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', r.id,
            'product_id', r.product_id,
            'user_id', r.user_id,
            'type', r.type,
            'quantity', r.quantity,
            'unit_price', r.unit_price,
            'total_price', r.total_price,
            'purchase_price', r.purchase_price,
            'sale_price', r.sale_price,
            'notes', r.notes,
            'created_at', r.created_at,
            'updated_at', r.updated_at,
            'product', r.product,
            'user', r."user"
          )
          order by r.created_at desc
        )
        from recent r
      ),
      '[]'::jsonb
    )
  );
$$;

create or replace function public.create_transaction_with_stock(
  p_product_id bigint,
  p_type text,
  p_quantity integer,
  p_unit_price numeric,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product public.products%rowtype;
  v_transaction public.transactions%rowtype;
  v_purchase_price numeric(10, 2);
  v_sale_price numeric(10, 2);
  v_app_user_id bigint;
begin
  if p_type not in ('in', 'out') then
    raise exception 'Le type de transaction doit être in ou out';
  end if;

  if p_quantity is null or p_quantity <= 0 then
    raise exception 'La quantité doit être supérieure à zéro';
  end if;

  v_app_user_id := public.current_app_user_id();
  if v_app_user_id is null then
    raise exception 'Utilisateur applicatif introuvable pour cette session';
  end if;

  select *
  into v_product
  from public.products
  where id = p_product_id
  for update;

  if not found then
    raise exception 'Produit introuvable';
  end if;

  if p_type = 'out' and v_product.stock_quantity < p_quantity then
    raise exception 'Stock insuffisant';
  end if;

  v_purchase_price := case
    when p_type = 'in' then p_unit_price
    else v_product.purchase_price
  end;

  v_sale_price := case
    when p_type = 'out' then p_unit_price
    else v_product.sale_price
  end;

  insert into public.transactions (
    product_id,
    user_id,
    type,
    quantity,
    unit_price,
    total_price,
    purchase_price,
    sale_price,
    notes
  )
  values (
    p_product_id,
    v_app_user_id,
    p_type,
    p_quantity,
    p_unit_price,
    p_quantity * p_unit_price,
    v_purchase_price,
    v_sale_price,
    p_notes
  )
  returning *
  into v_transaction;

  update public.products
  set
    stock_quantity = stock_quantity + case when p_type = 'in' then p_quantity else -p_quantity end,
    purchase_price = case when p_type = 'in' then p_unit_price else purchase_price end,
    updated_at = timezone('utc', now())
  where id = p_product_id;

  return (
    select jsonb_build_object(
      'id', t.id,
      'product_id', t.product_id,
      'user_id', t.user_id,
      'type', t.type,
      'quantity', t.quantity,
      'unit_price', t.unit_price,
      'total_price', t.total_price,
      'purchase_price', t.purchase_price,
      'sale_price', t.sale_price,
      'notes', t.notes,
      'created_at', t.created_at,
      'updated_at', t.updated_at,
      'product', jsonb_build_object(
        'id', p.id,
        'category_id', p.category_id,
        'name', p.name,
        'slug', p.slug,
        'description', p.description,
        'price', p.price,
        'stock_quantity', p.stock_quantity,
        'minimum_stock', p.minimum_stock,
        'barcode', p.barcode,
        'image_path', p.image_path,
        'purchase_price', p.purchase_price,
        'sale_price', p.sale_price,
        'created_at', p.created_at,
        'updated_at', p.updated_at,
        'category', jsonb_build_object(
          'id', c.id,
          'name', c.name,
          'slug', c.slug,
          'description', c.description,
          'created_at', c.created_at,
          'updated_at', c.updated_at
        )
      ),
      'user', jsonb_build_object(
        'id', u.id,
        'name', u.name,
        'email', u.email,
        'role', u.role
      )
    )
    from public.transactions t
    join public.products p on p.id = t.product_id
    join public.categories c on c.id = p.category_id
    join public.users u on u.id = t.user_id
    where t.id = v_transaction.id
  );
end;
$$;

create or replace function public.get_dashboard_data()
returns jsonb
language sql
stable
as $$
  with low_stock as (
    select *
    from public.products
    where stock_quantity <= minimum_stock
  ),
  top_products as (
    select
      t.product_id,
      sum(t.quantity)::int as total_quantity,
      sum(t.sale_price * t.quantity) as total_sales,
      sum((t.sale_price - t.purchase_price) * t.quantity) as total_profit
    from public.transactions t
    where t.type = 'out'
      and t.deleted_at is null
    group by t.product_id
    order by total_quantity desc
    limit 5
  ),
  recent_transactions as (
    select t.*
    from public.transactions t
    where t.deleted_at is null
    order by t.created_at desc
    limit 5
  )
  select jsonb_build_object(
    'lowStockProducts',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', p.id,
            'category_id', p.category_id,
            'name', p.name,
            'slug', p.slug,
            'description', p.description,
            'price', p.price,
            'stock_quantity', p.stock_quantity,
            'minimum_stock', p.minimum_stock,
            'barcode', p.barcode,
            'image_path', p.image_path,
            'purchase_price', p.purchase_price,
            'sale_price', p.sale_price,
            'created_at', p.created_at,
            'updated_at', p.updated_at,
            'category', jsonb_build_object(
              'id', c.id,
              'name', c.name,
              'slug', c.slug,
              'description', c.description,
              'created_at', c.created_at,
              'updated_at', c.updated_at
            )
          )
          order by p.created_at desc
        )
        from low_stock p
        join public.categories c on c.id = p.category_id
      ),
      '[]'::jsonb
    ),
    'totalProducts', (select count(*) from public.products),
    'totalValue', coalesce((select sum(price * stock_quantity) from public.products), 0),
    'recentTransactions',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', t.id,
            'product_id', t.product_id,
            'user_id', t.user_id,
            'type', t.type,
            'quantity', t.quantity,
            'unit_price', t.unit_price,
            'total_price', t.total_price,
            'purchase_price', t.purchase_price,
            'sale_price', t.sale_price,
            'notes', t.notes,
            'created_at', t.created_at,
            'updated_at', t.updated_at,
            'product', jsonb_build_object(
              'id', p.id,
              'category_id', p.category_id,
              'name', p.name,
              'slug', p.slug,
              'description', p.description,
              'price', p.price,
              'stock_quantity', p.stock_quantity,
              'minimum_stock', p.minimum_stock,
              'barcode', p.barcode,
              'image_path', p.image_path,
              'purchase_price', p.purchase_price,
              'sale_price', p.sale_price,
              'created_at', p.created_at,
              'updated_at', p.updated_at
            )
          )
          order by t.created_at desc
        )
        from recent_transactions t
        join public.products p on p.id = t.product_id
      ),
      '[]'::jsonb
    ),
    'transactionStats', jsonb_build_object(
      'total', (select count(*) from public.transactions where deleted_at is null),
      'in', (select count(*) from public.transactions where type = 'in' and deleted_at is null),
      'out', (select count(*) from public.transactions where type = 'out' and deleted_at is null),
      'today', (
        select count(*)
        from public.transactions
        where deleted_at is null
          and created_at::date = current_date
      ),
      'this_week', (
        select count(*)
        from public.transactions
        where deleted_at is null
          and created_at >= date_trunc('week', now())
          and created_at < date_trunc('week', now()) + interval '7 days'
      ),
      'this_month', (
        select count(*)
        from public.transactions
        where deleted_at is null
          and date_trunc('month', created_at) = date_trunc('month', now())
      )
    ),
    'financialStats', jsonb_build_object(
      'total_purchases', coalesce((select sum(purchase_price * quantity) from public.transactions where type = 'in' and deleted_at is null), 0),
      'total_sales', coalesce((select sum(sale_price * quantity) from public.transactions where type = 'out' and deleted_at is null), 0),
      'total_profit', coalesce((select sum((sale_price - purchase_price) * quantity) from public.transactions where type = 'out' and deleted_at is null), 0),
      'monthly_sales', coalesce((
        select sum(sale_price * quantity)
        from public.transactions
        where type = 'out'
          and deleted_at is null
          and date_trunc('month', created_at) = date_trunc('month', now())
      ), 0),
      'monthly_profit', coalesce((
        select sum((sale_price - purchase_price) * quantity)
        from public.transactions
        where type = 'out'
          and deleted_at is null
          and date_trunc('month', created_at) = date_trunc('month', now())
      ), 0)
    ),
    'topProducts',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'product_id', tp.product_id,
            'total_quantity', tp.total_quantity,
            'total_sales', tp.total_sales,
            'total_profit', tp.total_profit,
            'product', jsonb_build_object(
              'id', p.id,
              'category_id', p.category_id,
              'name', p.name,
              'slug', p.slug,
              'description', p.description,
              'price', p.price,
              'stock_quantity', p.stock_quantity,
              'minimum_stock', p.minimum_stock,
              'barcode', p.barcode,
              'image_path', p.image_path,
              'purchase_price', p.purchase_price,
              'sale_price', p.sale_price,
              'created_at', p.created_at,
              'updated_at', p.updated_at
            )
          )
          order by tp.total_quantity desc
        )
        from top_products tp
        join public.products p on p.id = tp.product_id
      ),
      '[]'::jsonb
    ),
    'stockByCategory',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', c.id,
            'name', c.name,
            'slug', c.slug,
            'description', c.description,
            'created_at', c.created_at,
            'updated_at', c.updated_at,
            'products_count', count(p.id),
            'products_sum_stock_quantity', coalesce(sum(p.stock_quantity), 0)
          )
          order by c.created_at desc
        )
        from public.categories c
        left join public.products p on p.category_id = c.id
        group by c.id
      ),
      '[]'::jsonb
    ),
    'valueByCategory',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', c.id,
            'name', c.name,
            'slug', c.slug,
            'description', c.description,
            'created_at', c.created_at,
            'updated_at', c.updated_at,
            'products_sum_price', coalesce(sum(p.price * p.stock_quantity), 0)
          )
          order by c.created_at desc
        )
        from public.categories c
        left join public.products p on p.category_id = c.id
        group by c.id
      ),
      '[]'::jsonb
    ),
    'stockAlerts', jsonb_build_object(
      'total', (select count(*) from low_stock),
      'critical', (select count(*) from low_stock where stock_quantity = 0),
      'warning', (select count(*) from low_stock where stock_quantity > 0)
    )
  );
$$;

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.transactions enable row level security;

drop policy if exists "users_select_authenticated" on public.users;
create policy "users_select_authenticated"
on public.users
for select
to authenticated
using (true);

drop policy if exists "users_insert_own_row" on public.users;
create policy "users_insert_own_row"
on public.users
for insert
to authenticated
with check (auth_user_id = auth.uid());

drop policy if exists "users_update_own_row" on public.users;
create policy "users_update_own_row"
on public.users
for update
to authenticated
using (auth_user_id = auth.uid())
with check (auth_user_id = auth.uid());

drop policy if exists "categories_authenticated_all" on public.categories;
create policy "categories_authenticated_all"
on public.categories
for all
to authenticated
using (true)
with check (true);

drop policy if exists "products_authenticated_all" on public.products;
create policy "products_authenticated_all"
on public.products
for all
to authenticated
using (true)
with check (true);

drop policy if exists "transactions_authenticated_all" on public.transactions;
create policy "transactions_authenticated_all"
on public.transactions
for all
to authenticated
using (true)
with check (true);

grant usage on schema public to anon, authenticated;
grant select on public.users to authenticated;
grant insert, update on public.users to authenticated;
grant select, insert, update, delete on public.categories to authenticated;
grant select, insert, update, delete on public.products to authenticated;
grant select, insert, update, delete on public.transactions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.current_app_user_id() to authenticated;
grant execute on function public.get_low_stock_products() to authenticated;
grant execute on function public.get_transaction_statistics() to authenticated;
grant execute on function public.create_transaction_with_stock(bigint, text, integer, numeric, text) to authenticated;
grant execute on function public.get_dashboard_data() to authenticated;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "product_images_select" on storage.objects;
create policy "product_images_select"
on storage.objects
for select
to public
using (bucket_id = 'product-images');

drop policy if exists "product_images_insert" on storage.objects;
create policy "product_images_insert"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'product-images');

drop policy if exists "product_images_update" on storage.objects;
create policy "product_images_update"
on storage.objects
for update
to authenticated
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

drop policy if exists "product_images_delete" on storage.objects;
create policy "product_images_delete"
on storage.objects
for delete
to authenticated
using (bucket_id = 'product-images');
