name: gestcave
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  fl_chart: ^1.0.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  sqflite: ^2.4.2
  path: ^1.9.0
  flutter_svg: ^2.0.17
  workmanager: ^0.6.0
  connectivity_plus: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  titled_navigation_bar:
    git:
      url: https://github.com/rg4amia/titled_navigation_bar.git
      ref: main
  flutter_dotenv: ^5.1.0
  responsive_framework: ^1.5.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/static/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/static/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/static/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/static/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/static/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/static/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/static/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/static/Outfit-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
